format = """
[░▒▓](#a3aed2)\
[ 󰣇 ](bg:#a3aed2 fg:#090c0c)\
[](bg:#3ca35d fg:#a3aed2)\
$directory\
[](fg:#3ca35d bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$package\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#212736 bg:#1d2230)\
$time\
[](fg:#1d2230)\
\n$character"""

[package]
symbol = "  "
format = '[$symbol$version]($style)'
style = "fg:#f5b95f bg:#1d2230"


[directory]
style = "fg:#e3e5e5 bg:#3ca35d"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#3ca35d bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#3ca35d bg:#394260)]($style)'

[golang]
symbol = " "
style = "bg:#00ADD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#a0a9cb bg:#1d2230)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#a0a9cb bg:#1d2230)]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](fg:bold red bg:#1d2230)]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
